#%RAML 1.0
---

title: Individuals Matching
version: P1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals/matching:
  /:
    post:
      (annotations.sandboxData): !include sandbox/match-request.md
      displayName: Match an individual's details against HMRC data
      description: !include docs/match-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.scope): "read:individuals-matching"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-matching" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-matching scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      responses:
        200:
          description: The available resources to retrieve the matched individual's details
          body:
            application/json:
              example: !include examples/matched-individual-resources-200.json
              type: !include schemas/matched-individual-resources.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        403:
          body:
            application/json:
              type: types.errorResponse
              examples:
                Forbidden:
                  description: The individual's details provided did not match with HMRC’s records
                  value:
                    code: MATCHING_FAILED

  /{matchId}:
    uriParameters:
      matchId:
        description: A short-lived UUID, typically valid for several hours
        type: string
        example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
    get:
      displayName: Retrieve matched individual's details
      description: !include docs/matched-individual-endpoint-description.md
      is: [headers.acceptHeader]
      (annotations.sandboxData): !include sandbox/matched-individual-request.md
      (annotations.scope): "read:individuals-matching"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-matching" ] } ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token with the read:individuals-matching scope.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
      responses:
        200:
          description: The individual's details for the given match id
          body:
            application/json:
              example: !include examples/matched-individual-response-200.json
              type: !include schemas/matched-individual-response.json
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
